# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: It's Claudio
email: cjrojas@uc.cl
description: > # this means to ignore newlines until "baseurl:"
  The purpose of this site is to keep track of my advances in my master
  thesis in carrying on. Feel free to ask anything you want. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://claudiorojasborquez.github.io" # the base hostname & protocol for your site
twitter_username: mspectrum
github_username:  claudiorojasborquez

# Build settings
markdown: kramdown
